name: chat_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  path: ^1.8.0
  sqflite: ^2.3.0
  equatable: ^2.0.5
  either_dart: ^1.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cupertino_icons: ^1.0.6
  firebase_storage: ^11.5.6
  firebase_database: ^10.3.8
  cloud_firestore: ^4.13.6
  firebase_core_platform_interface: ^5.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  uuid: ^4.3.3
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/